' **********************************************************************
' * Author: Taha Burak TÜZÜN
' * It checks to make sure you have a proper document open.  
' * It checks & utilizes the user units.
' * It will add 3 separate properties or combine them all into one property.
' * It will optionally draw a 3D sketch for you.
' * 3D sketch original code from SW help.
' **********************************************************************

Dim arrBody As Variant
Dim i As Integer
Dim Part As SldWorks.ModelDoc2
Dim box As Variant
Dim swApp As SldWorks.SldWorks
Dim myTable As SldWorks.TableAnnotation
Dim drawingDoc As SldWorks.ModelDocExtension
Dim swSelMgr As SldWorks.SelectionMgr
Dim boolstatus As Boolean
Dim instance As IModelDocExtension



Sub main()

    Set swApp = Application.SldWorks
    Set Part = swApp.ActiveDoc
    Set drawingDoc = Part.Extension
    Set swSelMgr = Part.SelectionManager
    
    
    arrBody = Part.GetBodies2(swSolidBody, True)
    k = UBound(arrBody)
    Dim bb As Variant
    
        
    Set myTable = drawingDoc.InsertGeneralTableAnnotation(True, 0, 0, swBOMConfigurationAnchor_TopLeft, "", k + 2, 4)
        myTable.Text(0, 0) = "İsim"
        myTable.Text(0, 1) = "X"
        myTable.Text(0, 2) = "Y"
        myTable.Text(0, 3) = "Z"
        
        
    Dim tempBody As Body2
    For i = 0 To UBound(arrBody) Step 1
        Set tempBody = arrBody(i)
        bb = arrBody(i).GetBodyBox
        'arrBody(i).
        'MsgBox ("X = " & Abs(bb(0) - bb(3)) * 1000)
        'MsgBox ("Y = " & Abs(bb(1) - bb(4)) * 1000)
        'MsgBox ("Z = " & Abs(bb(2) - bb(5)) * 1000)
        X = Abs(bb(0) - bb(3)) * 1000
        Y = Abs(bb(1) - bb(4)) * 1000
        Z = Abs(bb(2) - bb(5)) * 1000
        
        X = Math.Round(X, 2)
        Y = Math.Round(Y, 2)
        Z = Math.Round(Z, 2)
        
        myTable.Text(i + 1, 0) = tempBody.Name
        myTable.Text(i + 1, 1) = X
        myTable.Text(i + 1, 2) = Y
        myTable.Text(i + 1, 3) = Z
        
                
    Next
    
End Sub
